# prometheus.yml
global:
  scrape_interval: 5m

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["172.20.0.5:9100"]
