# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
    # Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
    
    # Node
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
