{
 "title": "Node Light",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   { "name": "INS", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$INS\",job=\"$job\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$INS\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$INS\", job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$INS\", job=\"$job\"})) * 100"
    }
   ]
  },
  {
   "title": "Exporter Process CPU Usage",
   "type": "timeseries",
   "description": "Rate of CPU time used by the process exposing this metric (user + system mode)",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"$INS\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Exporter Processes Memory",
   "type": "timeseries",
   "description": "Tracks the memory usage of the process exposing this metric (e.g., node_exporter), including current virtual memory and maximum virtual memory limit",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$INS\",job=\"$job\"}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_virtual_memory_max_bytes{instance=\"$INS\",job=\"$job\"}",
     "legendFormat": "Virtual Memory Limit"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$INS\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$INS\",job=\"$job\"} - node_boot_time_seconds{instance=\"$INS\",job=\"$job\"}"
    }
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Actual CPU being used",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "1 - (sum(irate(node_cpu_seconds_total{instance=\"$INS\",job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$INS\",job=\"$job\"}) by (cpu))))",
     "legendFormat": "Actual usage"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "timeseries",
   "description": "Percentage of RAM being actually used",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes{instance=\"$INS\",job=\"$job\"} / node_memory_MemTotal_bytes{instance=\"$INS\",job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "timeseries",
   "description": "Percentage of disk being actually used",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(node_filesystem_size_bytes{device!~\"rootfs\"}) - sum(node_filesystem_avail_bytes{device!~\"rootfs\"})\n) / \nsum(node_filesystem_size_bytes{device!~\"rootfs\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}