{
 "title": "Node Exporter Simplified",
 "description": "Simplified version of the Node Exporter Full. Only shows the most essential metrics of the instance.",
 "tags": [ "Linux" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   { "name": "HOST", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$HOST\"} - node_boot_time_seconds{instance=\"$HOST\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes{}" }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$HOST\"}[5m])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 - (node_memory_MemAvailable_bytes{instance=\"$HOST\"} / node_memory_MemTotal_bytes{instance=\"$HOST\"}) * 100)"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{instance=\"$HOST\",device!~'rootfs'}) * 100) / sum(node_filesystem_size_bytes{instance=\"$HOST\",device!~'rootfs'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$HOST\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{instance=\"$HOST\",device!~'rootfs'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TimeSeries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Also by mode",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$HOST\", mode=\"idle\"}[5m])) / scalar(count(count(node_cpu_seconds_total{instance=\"$HOST\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "description": "Basic RAM usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * ((node_memory_MemTotal_bytes{instance=\"$HOST\"} - node_memory_MemAvailable_bytes{instance=\"$HOST\"}) / node_memory_MemTotal_bytes{instance=\"$HOST\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Usable disk",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{instance=\"$HOST\", device!~'rootfs'}) * 100) / sum(node_filesystem_size_bytes{instance=\"$HOST\", device!~'rootfs'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$HOST\"}[5m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$HOST\"}[5m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=\"$HOST\"}[5m])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"$HOST\"}[5m])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  }
 ]
}